defaultPort: 8080
logging:
  config:
    name: 'jens-johnson.com-logger'
aws:
  s3:
    blogImageBucket:
      name: 'jens-johnson.com-blogimages'
      defaultImagePrefix: 'default'
    blogContentBucket:
      name: 'jens-johnson.com-blogposts'
blog:
  maxTagsShown: 20
  maxFeaturedPostsShown: 3
