defaultPort: 8080
logging:
  defaultConfig:
    loggingOptions:
      name: 'jens-johnson.com-logger'
      destination: 1
aws:
  s3:
    blogImageBucket:
      name: 'jens-johnson.com-blogimages'
      defaultImagePrefix: 'default'
    blogContentBucket:
      name: 'jens-johnson.com-blogposts'
blog:
  maxTagsShown: 20
  maxFeaturedPostsShown: 3
