defaultPort: 8080
logging:
  defaultConfig:
    loggingOptions:
      name: 'jens-johnson.com-logger'
      destination: 1
blog:
  maxTagsShown: 20
  maxFeaturedPostsShown: 3
  contentBucketName: 'jens-johnson.com-blogposts'
  imageBucket:
    bucketName: 'jens-johnson.com-blogimages'
    defaultImagePrefix: 'default'

