logging:
  destination:
    directory: /Users/JJo175/Development/Personal/jens-johnson.com/logs/
    levels:
      info: info.log
      error: error.log
      debug: debug.log
server:
  port:
    default: 8080